name: Compile customqueries.json

on:
  push:
    branches: [ "main" ]
    paths: 
      - queries/**

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: sergeysova/jq-action@v2
        with:
          cmd: echo "{\"queries\"\:$(jq -s 'add' queries/top_10.json queries/hvt.json queries/owned.json queries/domain.json queries/users.json queries/group.json queries/computers.json queries/gpo.json queries/certificates.json queries/aad.json)}"
